apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: yapp-staging-ingress
  namespace: staging
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - host: dev-yapp.suitestudy.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: yapp-app-staging-service
            port:
              number: 8080
